# -------------------------------------------------
# Project created by QtCreator 2010-02-17T23:02:10
# -------------------------------------------------
QT += network
TARGET = NeronGPS_lx
TEMPLATE = app
SOURCES += src/zoomform.cpp \
    src/tracesegment.cpp \
    src/tracerecorder.cpp \
    src/tracepainter.cpp \
    src/trace.cpp \
    src/tiletransaction.cpp \
    src/tileserverdirect.cpp \
    src/tileserver.cpp \
    src/tileref.cpp \
    src/tilemap.cpp \
    src/tilel3cachemux.cpp \
    src/tilel3cache.cpp \
    src/tilel2cache.cpp \
    src/tilel1cache.cpp \
    src/tilehttpwheel.cpp \
    src/tilehttptrans.cpp \
    src/tilehttpname.cpp \
    src/tilehttpmux.cpp \
    src/tilehttp.cpp \
    src/tilecontainer.cpp \
    src/tilecompressed.cpp \
    src/tilecompotrans.cpp \
    src/tilecomposer.cpp \
    src/tileclient.cpp \
    src/tilebatchloader.cpp \
    src/tileasyncloader.cpp \
    src/tile.cpp \
    src/threadmanager.cpp \
    src/thread.cpp \
    src/textfeeder.cpp \
    src/settings.cpp \
    src/serverform.cpp \
    src/poiserver.cpp \
    src/poiform.cpp \
    src/painterelement.cpp \
    src/painter.cpp \
    src/nmeaparser.cpp \
    src/nerongps.cpp \
    src/messagefeeder.cpp \
    src/messageboard.cpp \
    src/mapwidget.cpp \
    src/maptrailer.cpp \
    src/maptraces.cpp \
    src/maptarget.cpp \
    src/mapdrawlist.cpp \
    src/mapcursor.cpp \
    src/mapcross.cpp \
    src/mapcentering.cpp \
    src/magnificateform.cpp \
    src/logform.cpp \
    src/logfeeder.cpp \
    src/log.cpp \
    src/keyboardform.cpp \
    src/keyboard.cpp \
    src/journeyform.cpp \
    src/gpxloader.cpp \
    src/gpxform.cpp \
    src/gpxbuilder.cpp \
    src/gpsstatistics.cpp \
    src/gpsstate.cpp \
    src/gpssourcenmea.cpp \
    src/gpssample.cpp \
    src/gpsdata.cpp \
    src/gpsclock.cpp \
    src/global.cpp \
    src/drawstate.cpp \
    src/directory.cpp \
    src/converter.cpp \
    src/clockform.cpp \
    src/cacheform.cpp \
    src/buttonsboard.cpp \
    src/button.cpp \
    src/actionsmanager.cpp \
    qtlinux/main.cpp \
    qtlinux/platform.cpp
HEADERS += include/zoomform.h \
    include/tracesegment.h \
    include/tracerecorder.h \
    include/tracepainter.h \
    include/trace.h \
    include/tiletransaction.h \
    include/tileserverdirect.h \
    include/tileserver.h \
    include/tileref.h \
    include/tilemap.h \
    include/tilel3cachemux.h \
    include/tilel3cache.h \
    include/tilel2cache.h \
    include/tilel1cache.h \
    include/tilehttpwheel.h \
    include/tilehttptrans.h \
    include/tilehttpname.h \
    include/tilehttpmux.h \
    include/tilehttp.h \
    include/tilecontainer.h \
    include/tilecompressed.h \
    include/tilecompotrans.h \
    include/tilecomposer.h \
    include/tileclient.h \
    include/tilebatchloader.h \
    include/tileasyncloader.h \
    include/tile.h \
    include/threadmanager.h \
    include/thread.h \
    include/textfeeder.h \
    include/settings.h \
    include/serverform.h \
    include/poiserver.h \
    include/poiform.h \
    include/platform.h \
    include/painterelement.h \
    include/painter.h \
    include/nmeaparser.h \
    include/nerongps.h \
    include/messagefeeder.h \
    include/messageboard.h \
    include/mapwidget.h \
    include/maptrailer.h \
    include/maptraces.h \
    include/maptarget.h \
    include/mapdrawlist.h \
    include/mapcursor.h \
    include/mapcross.h \
    include/mapcentering.h \
    include/magnificateform.h \
    include/logform.h \
    include/logfeeder.h \
    include/log.h \
    include/keyboardform.h \
    include/keyboard.h \
    include/journeyform.h \
    include/gpxloader.h \
    include/gpxform.h \
    include/gpxbuilder.h \
    include/gpsstatistics.h \
    include/gpsstate.h \
    include/gpssourcenmea.h \
    include/gpssource.h \
    include/gpssample.h \
    include/gpsdata.h \
    include/gpsclock.h \
    include/global.h \
    include/drawstate.h \
    include/directory.h \
    include/converter.h \
    include/clockform.h \
    include/cacheform.h \
    include/buttonsboard.h \
    include/button.h \
    include/actionsmanager.h
FORMS += ui/zoomform.ui \
    ui/serverform.ui \
    ui/poiform.ui \
    ui/magnificateform.ui \
    ui/logform.ui \
    ui/keyboardform.ui \
    ui/journeyform.ui \
    ui/gpxform.ui \
    ui/clockform.ui \
    ui/cacheform.ui
